'''
Attribute List:
   hp, hpPerLevel, hpRegen, hpRegenPerLevel, mp, mpPerLevel, mpRegen, mpRegenPerLevel, armor, 
   armorPerLevel, mr, mrPerLevel, moveSpeed, lifeSteal, lethality, armorPen, magicPen, 
   critChance, attackSpeed, attackSpeedPerLevel (Percenergytage), attackDamage, attackDamagePerLevel, 
   abilityPower, CDR, energyergy, energyRegen, goldCost, additionalEffects
'''
   
champions = {
<<<<<<< mattackSpeedter
	"Aatrox": {
		"hp":580, 
		"hpPerLevel":80,
		"hpRegen":5, 
		"hpRegenPerLevel":0.25,
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0, 
		"mpRegenPerLevel":0,
		"armor":33,
		"armorPerLevel":3.25, 
		"mr":32.1,
		"mrPerLevel":1.25,
		"moveSpeed":345, 
		"lifeSteal":0,
		"lethality":0, 
		"armorPen":0, 
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0.651, 
		"attackSpeedPerLevel":0.025, 
		"attackDamage":60, 
		"attackDamagePerLevel":5,
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ahri": {
		"hp":526,
		"hpPerLevel":92,
		"hpRegen":6.5, 
		"hpRegenPerLevel":0.6,
		"mp":418,
		"mpPerLevel":25,
		"mpRegen":8, 
		"mpRegenPerLevel":0.8, 
		"armor":20.88,
		"armorPerLevel":3.5,
		"mr":30, 
		"mrPerLevel":0.5,
		"moveSpeed":330,
		"lifeSteal":0,
		"lethality":0, 
		"armorPen":0,
		"magicPen":0,
		"critChange":0,
		"attackSpeed":0.668, 
		"attackSpeedPerLevel":0.02,
		"attackDamage":53.04, 
		"attackDamagePerLevel":3,
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Akali":{
		"hp":550,
		"hpPerLevel":85, 
		"hpRegen":3.5, 
		"hpRegenPerLevel":0.5,
		"mp":0, "mpPerLevel":0, 
		"mpRegen":0,
		"mpRegenPerLevel":0, 
		"armor":23,
		"armorPerLevel":3.5,
		"mr":32.1,
		"mrPerLevel":1.25,
		"moveSpeed":345,
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0, 
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0.625, 
		"attackSpeedPerLevel":0.032,
		"attackDamage":62.4, 
		"attackDamagePerLevel":3.3,
		"abilityPower":0, 
		"CDR":0,
		"energy":200, 
		"energyRegen":50
	},
	"Alistar": {
		"hp":573.36,
		"hpPerLevel":106, 
		"hpRegen":8.5, 
		"hpRegenPerLevel":0.85,
		"mp":278.84,
		"mpPerLevel":38,
		"mpRegen":8.5, 
		"mpRegenPerLevel":0.8,
		"armor":44,
		"armorPerLevel":3.5,
		"mr":32.1, 
		"mrPerLevel":1.25,
		"moveSpeed":330, 
		"lifeSteal":0, 
		"lethality":0,
		"armorPen":0, 
		"magicPen":0,
		"critChange":0,
		"attackSpeed":0.625,
		"attackSpeedPerLevel":0.02125,
		"attackDamage":61.112, 
		"attackDamagePerLevel":3.62,
		"abilityPower":0,
		"CDR":0,
		"energy":0,
		"energyRegen":0
        },
	"Amumu": {
		"hp":613.12,
		"hpPerLevel":84,
		"hpRegen":9, 
		"hpRegenPerLevel":0.85,
		"mp":287.2, 
		"mpPerLevel":40,
		"mpRegen":7.382,
		"mpRegenPerLevel":0.525,
		"armor":33, 
		"armorPerLevel":3.8,
		"mr":32.1,
		"mrPerLevel":1.25,
		"moveSpeed":335, 
		"lifeSteal":0,
		"lethality":0, 
		"armorPen":0, 
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0.638,
		"attackSpeedPerLevel":'''15.3+2.18%''',
		"attackDamage":53.38, 
		"attackDamagePerLevel":3.8,
		"abilityPower":0,
		"CDR":0,
		"energy":0, 
		"energyRegen":0
	},
	"Anivia": {
		"hp":480, 
		"hpPerLevel":82,
		"hpRegen":5.5,
		"hpRegenPerLevel":0.55,
		"mp":495,
		"mpPerLevel":25, 
		"mpRegen":8,
		"mpRegenPerLevel":0.8,
		"armor":21.22,
		"armorPerLevel":4,
		"mr":30,
		"mrPerLevel":0.5,
		"moveSpeed":325,
		"lifeSteal":0,
		"lethality":0, 
		"armorPen":0, 
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0.625, 
		"attackSpeedPerLevel":0.0168,
		"attackDamage":51.376,
		"attackDamagePerLevel":3.2,
		"abilityPower":0, 
		"CDR":0,
		"energy":0, 
		"energyRegen":0
	},
	"Annie": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ashe": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Aurelion Sol": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Azir": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Bard": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Blitzcrank": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Brand": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Braum": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Caitlyn": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Camille": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Cassiopeia": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Cho'Gath": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Corki": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Darius": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Diana": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Dr. Mundo": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Draven": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ekko": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Elise": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Evelynn": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ezreal": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Fiddlesticks": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Fiora": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Fizz": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Galio": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Gangplank": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Garen": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Gnar": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Gragas": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Graves": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Hecarim": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Heimerdinger": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Illaoi": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Irelia": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ivern": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Janna": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Jarvan IV": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Jax": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Jayce": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Jhin": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Jinx": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kai'Sa": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kalista": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Karma": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Karthus": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kassadin": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Katarina": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kayle": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kayn": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kennen": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kha'Zix": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kindred": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kled": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Kog'Maw": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"LeBlanc": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Lee Sin": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Leona" :{
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Lissandra": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Lucian": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Lulu": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Lux": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Malphite": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Malzahar": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Maokai": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Master Yi": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Miss Fortune": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Mordekaiser": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Morgana": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Nami": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Nasus": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Nautilus": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Nidalee": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Nocturne": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Nunu & Willump": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Olaf": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Orianna": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ornn": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Pantheon": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Poppy": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Pyke": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Quinn": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Rakan": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Rammus": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Rek'Sai": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Renekton": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Rengar": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Riven": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Rumble": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ryze": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Sejuani": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Shaco": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Shen": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Shyvana": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Singed": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Sion": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Sivir": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Skarner": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Sona": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Soraka": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Swain": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Syndra": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Tahm Kench": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Taliyah": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Talon": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Taric": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Teemo": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Thresh": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Tristana": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Trundle": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Tryndamere": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Twisted Fate": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Twitch": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Udyr": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Urgot": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Varus": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Vayne": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Veigar": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Vel'Koz": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Vi": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Viktor": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Vladimir": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Volibear": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Warwick": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Wukong": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Xerath": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Xin Zhao": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Yasuo": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Yorick": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Zac": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Zed": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Ziggs": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Zilean": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Zoe": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
	"Zyra": {
		"hp":0,
		"hpPerLevel":0, 
		"hpRegen":0,
		"hpRegenPerLevel":0, 
		"mp":0,
		"mpPerLevel":0,
		"mpRegen":0,
		"mpRegenPerLevel":0,
		"armor":0, 
		"armorPerLevel":0,
		"mr":0, 
		"mrPerLevel":0,
		"moveSpeed":0, 
		"lifeSteal":0, 
		"lethality":0, 
		"armorPen":0,
		"magicPen":0, 
		"critChange":0, 
		"attackSpeed":0, 
		"attackSpeedPerLevel":0, 
		"attackDamage":0, 
		"attackDamagePerLevel":0, 
		"abilityPower":0, 
		"CDR":0, 
		"energy":0, 
		"energyRegen":0
	},
}


def lowercattackSpeede_all_dict_items():
	"""Convert all keys, values, and keys of values to lowercattackSpeede in the
	champions dictionary for user input validation. O(n*m) time O(1) space.
	"""
	champions = {key.lower(): value for key, value in champions.items()}
	for dictionary in champions:
		champions[dictionary] = {key.lower(): value for key, value in champions[dictionary].items()}

lowercattackSpeede_all_dict_items()

champions = {key.lower(): value for key, value in champions.items()}

for dictionary in champions:
	champions[dictionary] = {key.lower(): value for key, value in champions[dictionary].items()}
>>>>>>> mattackSpeedter


items = {
	"Abyssal Mask":{
		"hp":350, 
		"mp":300, 
		"mr":55, 
		"CDR":0.10, 
		"goldCost":3000
		"additionalEffects":'''"UNIQUE Passive - Eternity: 15% of damage taken from champions is
		gained as Mana. Spending Mana restores 20% of the cost as Health, up to 25 per spell cast.
		UNIQUE Aura: Neary enemy champions take 15% more magic damage."'''
	},
	"Adaptive Helm":{
		"hp":350,
		"mr":55,
		"mpRegen":1.00,
		"CDR":0.10,
		"goldCost":2800,
	},
	"Aegis of the Legion":{},
	"Aether Wisp":{},
	"Amplifying Tome":{},
	"Ancient Coin":{},
	"Arcane Sweeper":{},
	"Archangel's Staff":{},
	"Archangel's Staff (Quick Charge)":{},
	"Ardent Censer":{},
	"Athene's Unholy Grail":{},
	"Atma's Reckoning":{},
	"B. F. Sword":{},
	"Bami's Cinder":{},
	"Banshee's Veil":{},
	"Berserker's Greaves":{},
	"Bilgewater Cutlass":{},
	"Blade of the Ruined King":{},
	"Blasting Wand":{},
	"Boots of Mobility":{},
	"Boots of Speed":{},
	"Boots of Swiftness":{},
	"Bramble Vest":{},
	"Brawler's Gloves":{},
	"Broken Stopwatch":{},
	"Catalyst of Aeons":{},
	"Caulfield's Warhammer":{},
	"Chain Vest":{},
	"Chalice of Harmony":{},
	"Circlet of the Iron Solari":{},
	"Cloak of Stars":{},
	"Cloth Armor":{},
	"Commencing Stopwatch":{},
	"Control Ward":{},
	"Corrupting Potion":{},
	"Cosmic Shackle":{},
	"Crystalline Bracer":{},
	"Cull":{},
	"Dagger":{},
	"Dark Matter Scythe":{},
	"Dark Star Sigil":{},
	"Dead Man's Plate":{},
	"Death's Dance":{},
	"Death's Daughter":{},
	"Deathfire Grasp":{},
	"Dervish Blade":{},
	"Diet Poro-Snax":{},
	"Doran's Blade":{},
	"Doran's Lost Blade":{},
	"Doran's Lost Idol":{},
	"Doran's Lost Ring":{},
	"Doran's Lost Shield":{},
	"Doran's Ring":{},
	"Doran's Shield":{},
	"Duskblade of Draktharr":{},
	"Edge of Night":{},
	"Elixir of Iron":{},
	"Elixir of Sorcery":{},
	"Elixir of Wrath":{},
	"Entropy Field":{},
	"Espresso Snax":{},
	"Essence Reaver":{},
	"Executioner's Calling":{},
	"Explorer's Ward":{},
	"Eye of the Herald":{},
	"Faerie Charm":{},
	"Farsight Alteration":{},
	"Fiendish Codex":{},
	"Fire at Will":{},
	"Flash Zone":{},
	"Forbidden Idol":{},
	"Force of Nature":{},
	"Forgefire Cape":{},
	"Frosted Snax":{},
	"Frostfang":{},
	"Frozen Heart":{},
	"Frozen Mallet":{},
	"Gargoyle Stoneplate":{},
	"Ghost Poro":{},
	"Ghostwalkers (Melee Only)":{},
	"Giant's Belt":{},
	"Glacial Shroud":{},
	"Golden Transcendence":{},
	"Golden Transcendence (Disabled)":{},
	"Gravity Boots":{},
	"Greater Stealth Totem (Trinket)":{},
	"Greater Vision Totem (Trinket)":{},
	"Guardian Angel":{},
	"Guardian's Hammer":{},
	"Guardian's Horn":{},
	"Guardian's Orb":{},
	"Guinsoo's Rageblade":{},
	"Haunting Guise":{},
	"Health Potion":{},
	"Heart of Targon":{},
	"Hexdrinker":{},
	"Hextech GLP-800":{},
	"Hextech Gunblade":{},
	"Hextech Protobelt-01":{},
	"Hextech Revolver":{},
	"Hunter's Machete":{},
	"Hunter's Potion":{},
	"Hunter's Talisman":{},
	"Iceborn Gauntlet":{},
	"Infernal Mask":{},
	"Infinity Edge":{},
	"Innervating Locket":{},
	"Ionian Boots of Lucidity":{},
	"Jaurim's Fist":{},
	"Kindlegem":{},
	"Kercheis Shard":{},
	"Knight's Vow":{},
	"Last Whisper":{},
	"Liandry's Torment":{},
	"Lich Bane":{},
	"Lifeline":{},
	"Locket of the Iron Solari":{},
	"Long Sword":{},
	"Lord Dominik's Regards":{},
	"Lord Van Damm's Pillager":{},
	"Lost Chapter":{},
	"Luden's Echo":{},
	"Manamune":{},
	"Manamune (Quick Charge)":{},
	"Maw of Malmortius":{},
	"Mejai's Soulstealer":{},
	"Mercurial Scimitar":{},
	"Mercury's Treads":{},
	"Mikael's Crucible":{},
	"Molten Edge":{},
	"Moonflair Spellblade":{},
	"Morellonomicon":{},
	"Mortal Reminder":{},
	"Muramana":{},
	"Nashor's Tooth":{},
	"Needlessly Large Rod":{},
	"Negatron Cloak":{},
	"Ninja Tabi":{},
	"Nomad's Medallion":{},
	"Null-Magic Mantle":{},
	"Oblivion Orb":{},
	"Ohmwrecker":{},
	"Oracle Lens":{},
	"Oracle's Extract":{},
	"Overlord's Bloodmail":{},
	"Perfect Hex Core":{},
	"Phage":{},
	"Phantom Dancer":{},
	"Philosopher's Medallion":{},
	"Pickaxe":{},
	"Poacher's Dirk":{},
	"Poro-Snax":{},
	"Port Pad":{},
	"Pridestalker's Blade":{},
	"Prototype Hex Core":{},
	"Quicksilver Sash":{},
	"Rabadon's Deathcap":{},
	"Rabadon's Deathcrown":{},
	"Rainbow Snax Party Pack!":{},
	"Raise Morale":{},
	"Randuin's Omen":{},
	"Rapid Firecannon":{},
	"Raptor Cloak":{},
	"Ravenous Hydra":{},
	"Recurve Bow":{},
	"Redemption":{},
	"Refillable Potion":{},
	"Rejuvenation Bead":{},
	"Relic Shield":{},
	"Remnant of the Ascended":{},
	"Remnant of the Aspect":{},
	"Remnant of the Watchers":{},
	"Righteous Glory":{},
	"Rod of Ages":{},
	"Rod of Ages (Quick Charge)":{},
	"Ruby Crystal":{},
	"Runaan's Hurricane":{},
	"Rylai's Crystal Scepter":{},
	"Salvation":{},
	"Sanguine Blade":{},
	"Sapphire Crystal":{},
	"Seeker's Armguard":{},
	"Seer Stone (Trinket)":{},
	"Seraph's Embrace":{},
	"Serrated Dirk":{},
	"Sheen":{},
	"Shield Totem":{},
	"Shurelya's Reverie":{},
	"Siege Ballista":{},
	"Siege Sight Warder":{},
	"Siege Teleport":{},
	"Singularity Lantern":{},
	"Skirmisher's Sabre":{},
	"Slightly Magical Boots":{},
	"Sorcerer's Shoes":{},
	"Soul Anchor (Trinket)":{},
	"Spear of Shojin":{},
	"Spectral Cutlass":{},
	"Spectre's Cowl":{},
	"Spellbinder":{},
	"Spellthief's Edge":{},
	"Spirit Visage":{},
	"Stalker's Blade":{},
	"Stat-Stick of Stoicism":{},
	"Statikk Shiv":{},
	"Sterak's Gage":{},
	"Stinger":{},
	"Stopwatch":{},
	"Stormrazor":{},
	"Sunfire Cape":{},
	"Super Spicy Snax":{},
	"Sword of the Divine":{},
	"Targon's Brace":{},
	"Tear of the Goddess":{},
	"Tear of the Goddess (Quick Charge)":{},
	"The Black Cleaver":{},
	"The Black Spear":{},
	"The Bloodthirster":{},
	"The Dark Seal":{},
	"The Hex Core Mk-1":{},
	"The Hex Core Mk-2":{},
	"The Obsidian Cleaver":{},
	"Thornmail":{},
	"Tiamat":{},
	"Timeworn Ancient Coin":{},
	"Timeworn Face of the Mountain":{},
	"Timeworn Frost Queen's Claim":{},
	"Timeworn Frostfang":{},
	"Timeworn Nomad's Medallion":{},
	"Timeworn Relic Shield":{},
	"Timeworn Spellthief's Edge":{},
	"Timeworn Talisman of Ascension":{},
	"Timeworn Talisman of Ascension":{},
	"Timeworn Targon's Brace":{},
	"Titanic Hydra":{},
	"Total Biscuit of Rejuvenation":{},
	"Tower: Beam of Ruination":{},
	"Tower: Storm Bulwark":{},
	"Trinity Force":{},
	"Trinity Fusion":{},
	"Twin Shadows":{},
	"Vampiric Scepter":{},
	"Vanguard Banner":{},
	"Void Staff":{},
	"Warden's Mail":{},
	"Warding Totem (Trinket)":{},
	"Warmog's Armor":{},
	"Wicked Hatchet":{},
	"Wit's End":{},
	"Wooglet's Witchcap":{},
	"Wooglet's Witchcrown":{},
	"Wriggle's Lantern":{},
	"Youmuu's Ghostblade":{},
	"Zeal":{},
	"Zeke's Convergence":{},
	"Zephyr":{},
	"Zhonya's Hourglass":{},
	"Zhonya's Paradox":{},
	"Zz'Rot Portal":{},
}
